version: '2'
services:
    initialspringboot-mongodb:
        container_name: initialspringboot-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/initialSpringBoot/mongodb/:/data/db/
