version: '2'
services:
    initialspringboot-mongodb:
        container_name: initialspringboot-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb initialspringboot-mongodb-config
    initialspringboot-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    initialspringboot-mongodb-config:
        image: mongo:3.3.5
        container_name: initialspringboot-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
